### ISSUE TITLE
processes issue

### ISSUE THREAD

**Issue by xc611** [broadinstitute/longbow#117]
Requested 16 cores,  #SBATCH --ntasks=16

cannot find Process-18 (?)

[INFO 2022-02-24 19:20:19  segment] Invoked via: longbow segment -t 16
[INFO 2022-02-24 19:20:19 annotate] Invoked via: longbow annotate -t 16 1395T.ccs.bam
[INFO 2022-02-24 19:20:19 annotate] Running with 16 worker subprocess(es)
[INFO 2022-02-24 19:20:19  segment] Running with 16 worker subprocess(es)
[INFO 2022-02-24 19:20:19  segment] Using simple splitting mode.
[INFO 2022-02-24 19:20:19  extract] Invoked via: longbow extract -o extracted.bam
[INFO 2022-02-24 19:20:19  extract] Writing extracted read segments to: extracted.bam
[INFO 2022-02-24 19:20:19  extract] Including 2 flanking bases.
[INFO 2022-02-24 19:20:19 annotate] Annotating 2492060 reads
Process Process-18:
Traceback (most recent call last):
  File "/mnt/projects/CCR-SF/active/Software/tools/Anaconda/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/projects/CCR-SF/active/Software/tools/Anaconda/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/projects/CCR-SF/active/Software/tools/longbow/longbow-0.5.21/src/longbow/annotate/command.py", line 271, in _write_thread_fn
    segments = bam_utils.collapse_annotations(ppath)
  File "/mnt/projects/CCR-SF/active/Software/tools/longbow/longbow-0.5.21/src/longbow/utils/bam_utils.py", line 292, in collapse_annotations
    for i, seg in enumerate(path):
TypeError: 'NoneType' object is not iterable

**Comment by kvg** [comment]
Thank you for this report. Can you supply us some further information regarding the array model you're using, and perhaps a small excerpt from the input BAM file that we can use for testing?

**Comment by A-N-Other** [comment]
Hi @kvg ! I'm attempting to get `longbow` running on a dataset we've received today but have run into this same error. It does appear linked to the launching of the spawned processes and occurs with any number of processes I pass to `-t` ... e.g. here with `-t 1`:
```
conda create -n longbow python=3.7.9
conda activate longbow

# the latter two below are also required, I found, but aren't pulled for install automatically
pip install maslongbow ordered_set editdistance

longbow annotate \
  -t 1 \
  -p reads/m64045e_220830_173130.hifi_reads.bam.pbi \
  -o longbow/m64045e_220830_173130.annotated.bam \
  reads/m64045e_220830_173130.hifi_reads.bam
```
... dies with ...
```
[INFO 2022-09-01 10:55:09 annotate] Invoked via: longbow annotate -t 1 -f -p reads/m64045e_220830_173130.hifi_reads.bam.pbi -o longbow/m64045e_220830_173130.annotated.bam reads/m64045e_220830_173130.hifi_reads.bam
[INFO 2022-09-01 10:55:09 annotate] Running with 1 worker subprocess(es)
[INFO 2022-09-01 10:55:09 annotate] Annotating 1248705 reads
Progress:   0%|                                                       | 0/1248705 [00:00<?, ? read/s]
Process Process-3:
Traceback (most recent call last):
  File ".../miniconda3/envs/longbow/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File ".../miniconda3/envs/longbow/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File ".../miniconda3/envs/longbow/lib/python3.7/site-packages/longbow/annotate/command.py", line 272, in _write_thread_fn
    segments = bam_utils.collapse_annotations(ppath)
  File ".../miniconda3/envs/longbow/lib/python3.7/site-packages/longbow/utils/bam_utils.py", line 292, in collapse_annotations
    for i, seg in enumerate(path):
TypeError: 'NoneType' object is not iterable
[INFO 2022-09-01 10:58:55 annotate] Annotated 0 reads with 0 total sections.
[INFO 2022-09-01 10:58:55 annotate] Done. Elapsed time: 225.71s. Overall processing rate: 0.00 reads/s.
```
I've subsetted that BAM down to contain only 10 reads, which gives the same error. You can download it to play with here: https://www.dropbox.com/s/jhi0eexbmf2lh46/m64045e_220830_173130.hifi_reads.mini.bam?dl=0

**Comment by jonn-smith** [comment]
Hi @A-N-Other.  Thanks for the info.  I'll take a look in a bit.  

In the meantime, can you try pulling the latest code from github and setting up your environment with that codebase?  In the past week I've put in a few fixes that haven't yet been propagated down to our `pip` package.  They won't address this issue, but you should have them to prevent potential other problems.

**Comment by jonn-smith** [comment]
@jamesbayne I've been away for two weeks and am just catching up on things.  The analysis that I had to do is almost complete.  I'll probably get a chance to investigate this in the next couple of weeks.

**Comment by sjianing88** [comment]
Hi @jonn-smith  @jamesbayne , 
I am encountering a similar issue while using the longbow annotate command (longbow version 0.6.14). How did you manage to resolve it?

The error occurs when annotating a BAM file(using the test data). Below is the command I used and the corresponding error message:

Command: longbow annotate -o annotated1.bam tests/test data/mas15 test input.bam

[INFO 2025-12-24 23:39:07 annotate] Invoked via: longbow annotate -o annotated1.bam tests/test data/mas15 test input.bam
[INFO 2025-12-24 23:39:07 annotate] Running with 3 worker subprocess(es)
[INFO 2025-12-24 23:39:07 annotate] Annotating 8 reads
8% Progress: 0/8 [00:00<?，? read/s]
Process Process-5:
Traceback (most recent call last):
  File "/root/miniforge3/envs/longbow/lib/python3.7/multiprocessing/process.py", line 297, in bootstrap
    self.run()
  File "/root/miniforge3/envs/longbow/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self.kwargs)
  File "/root/miniforge3/envs/longbow/lib/python3.7/site-packages/longbow/annotate/command.py", line 272, in _write_thread
    fn_segments = bam_utils.collapse_annotations(path)
  File "/root/miniforge3/envs/longbow/lib/python3.7/site-packages/longbow/utils/bam_utils.py", line 292, in collapse_annotations
    for i, seg in enumerate(path):
TypeError: 'NoneType' object is not iterable

Any suggestions would be greatly appreciated. Thanks a lot!
